version: '2.0'
services:
  mongodb:
    build: ./mongodb  
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb/data/db:/data/db
    ports:
      - 27017:27017
  quill:
    build: .
    depends_on:
      - mongodb
    volumes:
      - ./:/quill
      - /quill/node_modules
      - /quill/app/client/build
      - /quill/app/client/plugins
    ports:
      - 3000:3000
    command: npm run dev